# -*- coding: utf-8 -*-
"""pdf_chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170ycikaAmQqcwQl-_2suGvDL_dfb0PtK
"""

import streamlit as st
from PyPDF2 import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
# 這裡就是妳原本報錯的地方，這行一定要有
from langchain.chains import ConversationalRetrievalChain
from langchain_community.chat_models import ChatOpenAI
from langchain.memory import ConversationBufferMemory
import os

# --- 1. 頁面設定 ---
st.set_page_config(page_title="My AI Research Assistant", page_icon="🤖")
st.header("🤖 Chat with your PDF (RAG Prototype)")

# --- 2. 側邊欄：設定與上傳 ---
with st.sidebar:
    st.title("Configuration")
    openai_api_key = st.text_input("Enter OpenAI API Key", type="password")
    uploaded_file = st.file_uploader("Upload your PDF here", type="pdf")

    st.markdown("---")
    st.markdown("""
    **How it works:**
    1. **Ingest**: Reads PDF text.
    2. **Split**: Chunks text.
    3. **Embed**: Converts to vectors.
    4. **Store**: Saves to FAISS.
    5. **Retrieve**: Finds answers.
    """)

# --- 3. 核心邏輯函數 ---

def get_pdf_text(pdf_docs):
    text = ""
    pdf_reader = PdfReader(pdf_docs)
    for page in pdf_reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text
    return text

def get_text_chunks(text):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000, chunk_overlap=200, length_function=len
    )
    return text_splitter.split_text(text)

def get_vectorstore(text_chunks, api_key):
    embeddings = OpenAIEmbeddings(openai_api_key=api_key)
    return FAISS.from_texts(texts=text_chunks, embedding=embeddings)

def get_conversation_chain(vectorstore, api_key):
    llm = ChatOpenAI(openai_api_key=api_key, temperature=0.5, model_name="gpt-3.5-turbo")
    memory = ConversationBufferMemory(memory_key='chat_history', return_messages=True)
    return ConversationalRetrievalChain.from_llm(
        llm=llm, retriever=vectorstore.as_retriever(), memory=memory
    )

# --- 4. 主程式邏輯 ---

if openai_api_key:
    if "conversation" not in st.session_state:
        st.session_state.conversation = None
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = None

    if uploaded_file is not None:
        if st.session_state.conversation is None:
            with st.spinner("Processing PDF..."):
                try:
                    raw_text = get_pdf_text(uploaded_file)
                    if not raw_text:
                        st.error("No text found in PDF.")
                    else:
                        text_chunks = get_text_chunks(raw_text)
                        vectorstore = get_vectorstore(text_chunks, openai_api_key)
                        st.session_state.conversation = get_conversation_chain(vectorstore, openai_api_key)
                        st.success("Done!")
                except Exception as e:
                    st.error(f"Error: {e}")

        user_question = st.text_input("Ask a question:")
        if user_question and st.session_state.conversation:
            with st.spinner("Thinking..."):
                response = st.session_state.conversation({'question': user_question})
                st.session_state.chat_history = response['chat_history']

            for i, message in enumerate(reversed(st.session_state.chat_history)):
                if i % 2 == 0:
                    st.markdown(f"🤖 **AI:** {message.content}")
                    st.markdown("---")
                else:
                    st.markdown(f"👤 **You:** {message.content}")
else:
    st.warning("Please enter your OpenAI API Key.")